### ISSUE TITLE
Not all steps are counted

### ISSUE THREAD

**Issue by kolaente** [SecUSo/privacy-friendly-pedometer#89]
Since upgrading to the latest version (2.4) the pedometer seems to count only very few steps.

For example, this is the number of steps it counted on a 25km hike:

![image](https://user-images.githubusercontent.com/13721712/127023054-51e4f396-7903-4137-a0b1-a43deafc4440.png)

From earlier hikes in the same range it should have counted something ~30k steps, not 3k.

Things I've tried:
* Disabled the energy optimization for the pedometer app
* I've installed [another pedometer app](https://f-droid.org/packages/de.j4velin.pedometer/) and had both running for the day today. The other app did record ~1500 steps while this one recorded 400.
* Played around with the new sensitivity settings and the "use the pedometer hardware" mode.

None of the above had any measurable effect. It looks like this is an issue of the app since the other one seems to work fine - not something with my phone.

**Comment by kolaente** [comment]
Maybe related to https://github.com/SecUSo/privacy-friendly-pedometer/issues/79

**Comment by RufioHugo** [comment]
OK - please add an user with problems;
Since Upgrade 2.2=>2.3=>2.4 the app doesn't count all steps ... except ... sometimes it counts 2-3k where there have been 193 - but mostly it simply counts 50-80% less since July
Mostly "older" hardware ...

Any hope for a solution "these days"?

**Comment by matthiasbeyer** [comment]
Can confirm on Android 11, two year old hardware. So ... Not really that much on "older" Hardware.

Sad. This app once was the best on fdroid for step counting. 😢

**Comment by schra** [comment]
I experienced the same problem that too few steps were counted on my S3 with version 2.4. I fixed it by going into the settings, then "General", and then turning on "Use phone's step counting hardware" (which was disabled). Not it works flawlessly again. Got this idea from https://github.com/SecUSo/privacy-friendly-pedometer/issues/79#issuecomment-879274672

**Comment by matthiasbeyer** [comment]
I get the impression that the best would be to just revert all patches from the last working release (which seems to be v1.0.5) until master and start again from there... :cry:

**Comment by kolaente** [comment]
@matthiasbeyer A git bisect might be the better solution.

**Comment by hvdwolf** [comment]
Pedometer worked great so far, but since 2.4 it doesn't count hardly any steps. This is on a Samsung A52 4G 128GB on Android 11.
Some little extra infro from my side.
When I keep the app in the foreground, it counts all steps. As soon as the app somehow moves to the background it stops counting. This is both with the pedometer step counter as with access to the internal step counting hardware that the Samsung A52 has.
So for some users it obviously works with the internal step counting hardware, as described above, but on my Samsung on Android 11, it doesn't. Next to that: the power consumption is suddenly enormously increased.

**Comment by jonas2515** [comment]
Same bug here on the Fairphone 3, luckily you can still get v1.0.5, I switched back to that now: https://github.com/SecUSo/privacy-friendly-pedometer/releases/tag/v1.0.5

**Comment by John-Nagle** [comment]
Also seeing this bug on an Android phone without step counting hardware since the "upgrade" to 2.4. Getting like 300 steps a day.

This app is now useless. Suggest backing off to the previous version.

**Comment by KaffeMyers** [comment]
Same bug on my previous phone (stock OS for OnePlus 6T) as my brand new one (grapheneos on Pixel 6).

**Comment by StevanWhite** [comment]
I am experiencing similar problems with a phone that doesn't have a hardware step counter.
And I don't understand... why do I input my step length...?
And why... if I change the step length, does the count of steps change?  Surely, a step is a step.
Unless...

Please explain the algorithm you use to detect steps.

I am looking at the code of AccelerometerStepDetectorService.
Explain to me if I am wrong: it is using the accelerometer sensor to guess the distance traveled, then dividing by my input step length to arrive at a number of steps.  Ouch.

That would NOT constitute "counting steps."

Here's what you should do:  use the accelerometer to determine a principal frequency within limited windows (of maybe 5-10 sec).
For a walking person, that principal frequency should correspond strongly to steps.  A little fudge should get you a very good guess at a number of steps in a given time period.

If all this doesn't mean anything to you, find yourself a graduate student in applied mathematics.  They should be able to help, or point you to someone who can.

I also have doubts about how effective the code in this class could be in integrating the accelerations to arrive at distance traveled.

**Comment by sleep-yearning** [comment]
Thank you all for the reporting, can you confirm that this is still happening with version 3.0.1?
Quite some issues have been resolved in the meantime. 
Thank you also for the detailed analysis of AccelerometerStepDetectorService @StevanWhite, we should probably look into this at some point.

**Comment by John-Nagle** [comment]
I installed 3.0.1. Zero step count at "Normal" sensitivity. Set sensitivity to "very high". Zero step count.

Android 8.0.0
CatPhones S41
